#!/bin/sh

#######################################################
#                                                     #
#   File to archive the Survey data base for Samoens  #
#                  by Xavier ROBERT                   #
#                      10/12/31                       #
#                                                     #
#######################################################


# If you want to change the name of the archive
OUTPUT=backup-samoens-GIS2014

# Make the Archive Structure
mkdir $OUTPUT
cp thconfig* $OUTPUT
cp tarngo.sh $OUTPUT
cp README $OUTPUT
cp vulcain.gif $OUTPUT
cp vulcain2.jpg $OUTPUT
cp config.thc $OUTPUT
mkdir $OUTPUT/CODES
cp CODES/Tro2Therion.tar.gz $OUTPUT/CODES
mkdir $OUTPUT/Samoens-GIS
mkdir $OUTPUT/Samoens-GIS/dem
cp Samoens-GIS/dem/*.th $OUTPUT/Samoens-GIS/dem
cp Samoens-GIS/dem/*.jpg $OUTPUT/Samoens-GIS/dem
mkdir $OUTPUT/Samoens-GIS/kmz
cp Samoens-GIS/kmz/*.kmz $OUTPUT/Samoens-GIS/kmz
cp Samoens-GIS/kmz/*.kml $OUTPUT/Samoens-GIS/kmz
mkdir $OUTPUT/Samoens-GIS/GPS
cp Samoens-GIS/GPS/*.GPX $OUTPUT/Samoens-GIS/GPS


# Build the structure by zones

####### RESEAU DU A21  ########

UPDIR=Reseau_A21
mkdir $OUTPUT/$UPDIR
cp $UPDIR/*.th $OUTPUT/$UPDIR
cp $UPDIR/*.th2 $OUTPUT/$UPDIR
cp $UPDIR/*thconfig* $OUTPUT/$UPDIR

# Zone A
DIRECTORY=zone-A
mkdir $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th2 $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY
	##   A21
TROU=A21	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   A22
TROU=A22
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   AV24
TROU=A24	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU


# Zone PV
DIRECTORY=zone-PV
mkdir $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th2 $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY


######### RESEAU DES AVOUDRUES - RESURGENCE DE LA GOUILLE

UPDIR=Avoudrues
mkdir $OUTPUT/$UPDIR
cp $UPDIR/*.th $OUTPUT/$UPDIR
cp $UPDIR/*.th2 $OUTPUT/$UPDIR
cp $UPDIR/*thconfig* $OUTPUT/$UPDIR


# Zone AV
DIRECTORY=zone-AV
mkdir $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th2 $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY

	##   AV8
TROU=AV8	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU


########## RESEAU DU JEAN-BERNARD  ###########
UPDIR=JB
mkdir $OUTPUT/$UPDIR
cp $UPDIR/*thconfig* $OUTPUT/$UPDIR


# JB
DIRECTORY=JB
mkdir $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/thconfig $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/jb.th $OUTPUT/$UPDIR/$DIRECTORY
mkdir $OUTPUT/$UPDIR/$DIRECTORY/Data-th
cp $UPDIR/$DIRECTORY/Data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/Data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone
	# Copy all the sub-maps
	mkdir $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/-900
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/-900/*.tro $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/-900
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/-900/*.doc $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/-900
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/-900/*.th* $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/-900
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/-900/thconfig $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/-900	
	mkdir $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/affluentC14
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/affluentC14/*.tro $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/affluentC14
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/affluentC14/*.doc $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/affluentC14
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/affluentC14/*.th* $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/affluentC14
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/affluentC14/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/affluentC14
	mkdir $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Arva
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/Arva/*.tro $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Arva
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/Arva/*.doc $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Arva
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/Arva/*.th* $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Arva
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/Arva/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Arva
	mkdir $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/aval-aiguilles
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/aval-aiguilles/*.tro $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/aval-aiguilles
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/aval-aiguilles/*.doc $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/aval-aiguilles
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/aval-aiguilles/*.th* $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/aval-aiguilles
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/aval-aiguilles/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/aval-aiguilles
	mkdir $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/dino
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/dino/*.tro $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/dino
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/dino/*.th* $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/dino
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/dino/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/dino
	mkdir $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Gourance2013
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/Gourance2013/*.tro $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Gourance2013
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/Gourance2013/*.doc $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Gourance2013
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/Gourance2013/*.th* $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Gourance2013
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/Gourance2013/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Gourance2013
	mkdir $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/LAVOIR-parts
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/LAVOIR-parts/*.tro $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/LAVOIR-parts
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/LAVOIR-parts/*.doc $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/LAVOIR-parts
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/LAVOIR-parts/*.th* $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/LAVOIR-parts
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/LAVOIR-parts/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/LAVOIR-parts

	mkdir $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Plafond-Gourance
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/Plafond-Gourance/*.tro $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Plafond-Gourance
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/Plafond-Gourance/*.doc $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Plafond-Gourance
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/Plafond-Gourance/*.th* $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Plafond-Gourance
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/Plafond-Gourance/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Plafond-Gourance
	mkdir $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Shunt-Branlots
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/Shunt-Branlots/*.tro $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Shunt-Branlots
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/Shunt-Branlots/*.doc $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Shunt-Branlots
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/Shunt-Branlots/*.th* $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Shunt-Branlots
	cp $UPDIR/$DIRECTORY/Data-th/Scrap-alone/Shunt-Branlots/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/Data-th/Scrap-alone/Shunt-Branlots
	# Rajouter en dessous les 5 lignes necessaires à la sauvegarde de chaque nouveaux bout topo dans le JB

mkdir $OUTPUT/$UPDIR/$DIRECTORY/Donnees-autres
cp $UPDIR/$DIRECTORY/Donnees-autres/*.tro $OUTPUT/$UPDIR/$DIRECTORY/Donnees-autres
cp $UPDIR/$DIRECTORY/Donnees-autres/Squelette-topo-partielles/*.tro $OUTPUT/$UPDIR/$DIRECTORY/Donnees-autres
cp $UPDIR/$DIRECTORY/Donnees-autres/Squelette-topo-partielles/Meandre-arianes/*.tro $OUTPUT/$UPDIR/$DIRECTORY/Donnees-autres
mkdir $OUTPUT/$UPDIR/$DIRECTORY/Drawing-th2
cp $UPDIR/$DIRECTORY/Drawing-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/Drawing-th2


# Zone B
DIRECTORY=zone-B
mkdir $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th2 $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY

	##   B3
TROU=B3
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   B10
TROU=B10
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT$UPDIR//$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU

# Zone C
DIRECTORY=zone-C
mkdir $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th2 $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY

	##   C6
TROU=C6
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   C14
TROU=C14
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   C24
TROU=C24
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   C31
TROU=C31
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   C42
TROU=C42
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   C44
TROU=C44
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   C51
TROU=C51
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   C52
TROU=C52
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   C74
TROU=C74
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   C75
TROU=C75
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   C114
TROU=C114
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU

# Zone CH
DIRECTORY=zone-CH
mkdir $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th2 $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY

	##   CH3
TROU=CH3
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   CH17
TROU=CH17
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   CH20
TROU=CH20
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   CH22
TROU=CH22
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   CH23
TROU=CH23
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   CH24
TROU=CH24
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU


# Zone D
DIRECTORY=zone-D
mkdir $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th2 $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY

	##   D11
TROU=D11
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   D33
TROU=D33
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU

# Zone F
DIRECTORY=zone-F
mkdir $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th2 $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY

# Zone V
DIRECTORY=zone-V
mkdir $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th2 $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY

	##   V4ter
TROU=V4ter
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU

# Prospection
DIRECTORY=Prospection
mkdir $OUTPUT/$UPDIR/$DIRECTORY

######## RESEAU DE LA COMBE AUX PUAIRES  #######

UPDIR=Combe-Puaires
mkdir $OUTPUT/$UPDIR
cp $UPDIR/*thconfig* $OUTPUT/$UPDIR

#_____#

# Zone BA
DIRECTORY=zone-BA
mkdir $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th2 $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY

	##   BA2
TROU=BA2
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
	##   BA4
TROU=BA4
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU


#_____#

# Zone CP
DIRECTORY=zone-CP
mkdir $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th2 $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY

	##   CP01
TROU=CP01	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   CP03
TROU=CP03
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   CP06
TROU=CP06
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   CP15
TROU=CP15	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   CP17
TROU=CP17	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   CP19
TROU=CP19	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   CP21
TROU=CP21
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $UPDIR/$OUTPUT/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   CP24
TROU=CP24	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   CP28a
TROU=CP28a	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   CP32
TROU=CP32	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   CP43
TROU=CP43	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   CP62
TROU=CP62	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   Reseau CP
TROU=Reseau-CP
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   Prospection
TROU=Prospection
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU

#_____#

# Zone DR
DIRECTORY=zone-DR
mkdir $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th2 $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY
	##   DR1
TROU=DR1	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2

	##   DR9
TROU=DR9	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   DR18
TROU=DR18
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2

#_____#

# Zone L
DIRECTORY=zone-L
mkdir $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th2 $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY

	##   L11
TROU=L11	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   L17
TROU=L17	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   L25
TROU=L25	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2


#_____#

# Zone LP
DIRECTORY=zone-LP
mkdir $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th2 $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY

	##   LP2
TROU=LP2	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   LP3
TROU=LP3	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   LP9
TROU=LP9
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   LP19
TROU=LP19
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   LP23
TROU=LP23	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2

	##   LP34
TROU=LP34	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2

	##   LP35
TROU=LP35	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2

#_____#

# Zone LS
DIRECTORY=zone-LS
mkdir $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th2 $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY

	##   LS22
TROU=LS22	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU



	##   LS30
TROU=LS30	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2

#_____#
# Zone T
DIRECTORY=zone-T
mkdir $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*.th2 $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY
	##   T9
TROU=T9	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   T25a-b
TROU=T25a-b	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
	##   T35
TROU=T35	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
   ## T59
TROU=T59	
mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/$TROU/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY/$TROU
#mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
#cp $UPDIR/$DIRECTORY/$TROU/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
#cp $UPDIR/$DIRECTORY/$TROU/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th
#mkdir $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2
#cp $UPDIR/$DIRECTORY/$TROU/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU/data-th2



#_____#

# Ermoy
DIRECTORY=Ermoy
mkdir $OUTPUT/$UPDIR/$DIRECTORY
#cp Ermoy/*.th $OUTPUT
cp $UPDIR/$DIRECTORY/*.th $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/$TROU/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/$TROU
cp $UPDIR/$DIRECTORY/*.tro $OUTPUT/$UPDIR/$DIRECTORY
cp $UPDIR/$DIRECTORY/*thconfig* $OUTPUT/$UPDIR/$DIRECTORY
mkdir $OUTPUT/$UPDIR/$DIRECTORY/data-th
cp $UPDIR/$DIRECTORY/data-th/*.th $OUTPUT/$UPDIR/$DIRECTORY/data-th
cp $UPDIR/$DIRECTORY/data-th/*.tro $OUTPUT/$UPDIR/$DIRECTORY/data-th
mkdir $OUTPUT/$UPDIR/$DIRECTORY/data-th2
cp $UPDIR/$DIRECTORY/data-th2/*.th2 $OUTPUT/$UPDIR/$DIRECTORY/data-th2

###############################################
# Zip the Archive
tar -cvf $OUTPUT.tar $OUTPUT
gzip $OUTPUT.tar

# Clean
rm -r $OUTPUT
